'use client';

interface Email {
  subject: string;
  body: string;
}

interface DownloadOptions {
  emails: Email[];
  filename?: string;
  style?: string;
  targetCompany?: string;
}

/**
 * Download all emails as a PDF file
 */
export async function downloadAsPDF({ emails, filename = 'generated-emails', style, targetCompany }: DownloadOptions): Promise<void> {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import('jspdf');
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Generated Cold Emails', margin, y);
  y += 10;

  // Metadata
  if (style || targetCompany) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    if (style) doc.text(`Style: ${style}`, margin, y);
    if (targetCompany) doc.text(`Target: ${targetCompany}`, margin + 80, y);
    y += 8;
    doc.setTextColor(0);
  }

  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  emails.forEach((email, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    // Email number
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(59, 130, 246); // Blue color
    doc.text(`Email ${index + 1}`, margin, y);
    y += 10;

    // Subject
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Subject:', margin, y);
    doc.setFont('helvetica', 'normal');
    const subjectLines = doc.splitTextToSize(email.subject, maxWidth - 25);
    doc.text(subjectLines, margin + 25, y);
    y += subjectLines.length * 6 + 8;

    // Body
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Body:', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    const bodyLines = doc.splitTextToSize(email.body, maxWidth);
    
    // Check if body will overflow
    const bodyHeight = bodyLines.length * 5;
    if (y + bodyHeight > 280) {
      doc.addPage();
      y = 20;
    }
    
    doc.text(bodyLines, margin, y);
    y += bodyHeight + 15;

    // Divider between emails
    if (index < emails.length - 1) {
      doc.setDrawColor(230);
      doc.line(margin, y - 5, pageWidth - margin, y - 5);
      y += 10;
    }
  });

  // Footer
  const date = new Date().toLocaleDateString();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by ColdlyBound on ${date}`, margin, 287);

  doc.save(`${filename}.pdf`);
}

/**
 * Download all emails as a DOC file (actually HTML that Word can open)
 */
export function downloadAsDOC({ emails, filename = 'generated-emails', style, targetCompany }: DownloadOptions): void {
  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Generated Cold Emails</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      color: #333;
    }
    h1 {
      color: #1a1a1a;
      border-bottom: 2px solid #3b82f6;
      padding-bottom: 10px;
    }
    .metadata {
      color: #666;
      font-size: 14px;
      margin-bottom: 20px;
    }
    .email {
      margin-bottom: 30px;
      padding: 20px;
      background: #f8fafc;
      border-left: 4px solid #3b82f6;
    }
    .email-number {
      color: #3b82f6;
      font-weight: bold;
      font-size: 16px;
      margin-bottom: 10px;
    }
    .subject {
      font-weight: bold;
      margin-bottom: 10px;
    }
    .subject span {
      font-weight: normal;
    }
    .body {
      white-space: pre-wrap;
      line-height: 1.6;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      color: #999;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <h1>Generated Cold Emails</h1>
  ${style || targetCompany ? `<div class="metadata">${style ? `Style: ${style}` : ''} ${targetCompany ? `| Target: ${targetCompany}` : ''}</div>` : ''}
`;

  emails.forEach((email, index) => {
    html += `
  <div class="email">
    <div class="email-number">Email ${index + 1}</div>
    <div class="subject"><strong>Subject:</strong> <span>${escapeHtml(email.subject)}</span></div>
    <div class="body">${escapeHtml(email.body)}</div>
  </div>
`;
  });

  html += `
  <div class="footer">Generated by ColdlyBound on ${new Date().toLocaleDateString()}</div>
</body>
</html>
`;

  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download current email only
 */
export async function downloadSingleEmailAsPDF(email: Email, index: number, style?: string, targetCompany?: string): Promise<void> {
  await downloadAsPDF({
    emails: [email],
    filename: `email-${index + 1}`,
    style,
    targetCompany,
  });
}

export function downloadSingleEmailAsDOC(email: Email, index: number, style?: string, targetCompany?: string): void {
  downloadAsDOC({
    emails: [email],
    filename: `email-${index + 1}`,
    style,
    targetCompany,
  });
}

function escapeHtml(text: string): string {
  if (typeof document === 'undefined') return text;
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
